version: "3"


services:
 pialert_staging:
    container_name: pialert_staging
    image: gitlab.baupal.ch:5050/infra/pialert_gl:staging

    environment:
      TZ: 'Europe/Zurich'
      PORT: 20223
      
    volumes:
      - 'staging_config_st:/home/pi/pialert/config'
      - 'staging_db_st:/home/pi/pialert/db'
      - 'staging_logs_st:/home/pi/pialert/front/log'
      #- '/home/pi/gitrepos/pialert_gl/front/plugins/unifi_import/script.py:/home/pi/pialert/front/plugins/unifi_import/script.py'
      #- '/home/pi/gitrepos/pialert_gl/front/plugins/unifi_import/config.json:/home/pi/pialert/front/plugins/unifi_import/config.json'
      - '/var/lib/docker/volumes/pihole/_data/pihole-FTL.db:/etc/pihole/pihole-FTL.db:ro'
      - '/var/lib/docker/volumes/pihole/_data/dhcp.leases:/etc/pihole/dhcp.leases:ro'
    network_mode: "host"
      
    restart: unless-stopped

volumes:
  staging_config_st:
  staging_db_st:
  staging_logs_st:
  
