site_name: NetAlertX Docs
site_url: https://jokob-sk.github.io/NetAlertX/
repo_url: https://github.com/jokob-sk/NetAlertX/
edit_uri: blob/main/docs/
docs_dir: docs
site_description: >-
  The main documentation resource for NetAlertX - a network scanner and presence detector
# static_dir: docs/img
nav:
  - Home: index.md

  - Installation: 
      - Installation options: INSTALLATION.md
      - Quick setup: INITIAL_SETUP.md      
      - Docker:
        - Docker Guide: https://github.com/jokob-sk/NetAlertX/blob/main/dockerfiles/README.md    
        - Docker Compose: DOCKER_COMPOSE.md
        - Docker File Permissions: FILE_PERMISSIONS.md
        - Docker Updates: UPDATES.md
      - Other:
        - Synology Guide: SYNOLOGY_GUIDE.md
        - Community Guides: COMMUNITY_GUIDES.md
        - Bare-metal (Experimental): HW_INSTALL.md
        - Migration Guide: MIGRATION.md
      - Help:
        - Common issues: COMMON_ISSUES.md      
  - Setup:
      - Getting started:
        - Subnets: SUBNETS.md
        - Enable Plugins: PLUGINS.md  
        - Pi-hole Guide: PIHOLE_GUIDE.md
        - Home Assistant: HOME_ASSISTANT.md
        - Emails: SMTP.md
        - Backups: BACKUPS.md   
      - Advanced guides:
        - Remote Networks: REMOTE_NETWORKS.md      
        - Notifications Guide: NOTIFICATIONS.md        
        - Authelia: AUTHELIA.md   
        - Performance: PERFORMANCE.md      
        - Reverse DNS: REVERSE_DNS.md  
        - Reverse Proxy: REVERSE_PROXY.md
        - Webhooks (n8n): WEBHOOK_N8N.md
      - Help:
        - Common issues: COMMON_ISSUES.md
        - Random MAC: RANDOM_MAC.md
      
  - Device guides:
      - Editing Devices:
        - Management: DEVICE_MANAGEMENT.md
        - Bulk Editing: DEVICES_BULK_EDITING.md
        - Custom Properties: CUSTOM_PROPERTIES.md
        - Device Display Settings: DEVICE_DISPLAY_SETTINGS.md
        - Session Info: SESSION_INFO.md
      - Icons and Topology:
        - Icons: ICONS.md
        - Network Topology: NETWORK_TREE.md
  - Troubleshooting:
      - Debugging Tips: DEBUG_TIPS.md
      - Debugging Invalid JSON: DEBUG_INVALID_JSON.md
      - Debugging Plugins: DEBUG_PLUGINS.md
      - Debugging Web UI Port: WEB_UI_PORT_DEBUG.md
  - Development:
      - Plugin and app development:
        - Environment Setup: DEV_ENV_SETUP.md
        - Custom Plugins: PLUGINS_DEV.md
        - Frontend Development: FRONTEND_DEVELOPMENT.md
        - Database: DATABASE.md
        - Settings: SETTINGS_SYSTEM.md
        - Versions: VERSIONS.md
      - Integrations:
        - Webhook Secret: WEBHOOK_SECRET.md
        - API: API.md     


theme:
  name: material
  logo: img/NetAlertX_logo.png  # Reference the favicon here
  favicon: img/NetAlertX_logo.png
  metadata:
    description: "NetAlertX Documentation - The go-to resource for all things related to NetAlertX."
    image: "https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/front/img/NetAlertX_logo.png"
  extra:
    home_hide_sidebar: true
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/jokob-sk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/jokobsk/netalertx/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/NetAlertX
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: slate  # Default to dark mode
      primary: indigo  # Dark blue
      accent: deep-purple  # Adjust accent color if needed
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default  # Light mode (optional)
      primary: black
      accent: deep-purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
markdown_extensions:
  - admonition
plugins:
  - gh-admonitions
  - search

favicon: /img/NetAlertX_logo.png
