site_name: NetAlertX Docs
site_url: https://jokob-sk.github.io/NetAlertX/
nav:
  - Home: README.md
  - API: API.md
  - Authentication:
      - Authelia: AUTHELIA.md
  - Backups: BACKUPS.md
  - Community Guides: COMMUNITY_GUIDES.md
  - Customization:
      - Custom Properties: CUSTOM_PROPERTIES.md
      - Device Display Settings: DEVICE_DISPLAY_SETTINGS.md
  - Database:
      - Overview: DATABASE.md
      - Performance: PERFORMANCE.md
  - Debugging:
      - Debugging Invalid JSON: DEBUG_INVALID_JSON.md
      - Debugging Plugins: DEBUG_PLUGINS.md
      - Debugging Tips: DEBUG_TIPS.md
  - Development:
      - Setup: DEV_ENV_SETUP.md
      - Frontend Development: FRONTEND_DEVELOPMENT.md
  - Devices:
      - Management: DEVICE_MANAGEMENT.md
      - Bulk Editing: DEVICES_BULK_EDITING.md
      - Random MAC: RANDOM_MAC.md
  - Docker:
      - Docker Compose: DOCKER_COMPOSE.md
      - File Permissions: FILE_PERMISSIONS.md
  - Home Assistant: HOME_ASSISTANT.md
  - Hardware:
      - Installation: HW_INSTALL.md
  - Icons: ICONS.md
  - Migration Guide: MIGRATION.md
  - Network:
      - Tree: NETWORK_TREE.md
      - Remote Networks: REMOTE_NETWORKS.md
      - Subnets: SUBNETS.md
      - Reverse DNS: REVERSE_DNS.md
  - Notifications:
      - Overview: NOTIFICATIONS.md
      - SMTP: SMTP.md
  - Performance: PERFORMANCE.md
  - Pi-hole Guide: PIHOLE_GUIDE.md
  - Plugins:
      - Development: PLUGINS_DEV.md
      - Webhook (n8n): WEBHOOK_N8N.md
      - Webhook Secret: WEBHOOK_SECRET.md
  - Proxy & Reverse DNS:
      - Reverse Proxy: REVERSE_PROXY.md
  - Session Info: SESSION_INFO.md
  - Settings:
      - System Settings: SETTINGS_SYSTEM.md
  - Synology Guide: SYNOLOGY_GUIDE.md
  - Updates & Versions:
      - Updates: UPDATES.md
      - Versions: VERSIONS.md
  - Web UI:
      - Debugging Web UI Port: WEB_UI_PORT_DEBUG.md