name: Feature Request
description: 'Suggest an idea for NetAlertX'
labels: ['Feature request➕']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an open or closed issue already exists for the feature you are requesting. 
    options:
    - label: I have searched the existing open and closed issues
      required: true
- type: checkboxes
  attributes:
    label: Am I willing to test this? 🧪
    description: I rely on the community to test unreleased features. If you are requesting a feature, please be willing to test it within 48h of test request. Otherwise, the feature might be pulled from the code base. 
    options:
    - label: I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.
      required: true
- type: checkboxes
  attributes:
    label: Can I help implement this? 👩‍💻👨‍💻 
    description: The maintainer will provide guidance and help. The implementer will read the PR guidelines https://github.com/jokob-sk/NetAlertX/tree/main/docs#-pull-requests-prs
    options:
    - label: "Yes"
    - label: "No"
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Mockups? Anything that will give us more context about the feature you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
