name: Code checks
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main

jobs:
  check-url-paths:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for absolute path URLs
        run: |
          if grep -rE "['\"]\/php\/" --include=\*.{js,php} .; then
            echo "❌ Found absolute path URLs starting with '/php/'. Please use relative paths."
            exit 1
          else
            echo "✅ No absolute path URLs found."
          fi

      - name: Check Python syntax
        run: |
          set -e
          echo "🔍 Checking Python syntax..."
          find . -name "*.py" -print0 | xargs -0 -n1 python3 -m py_compile

